theme: jekyll-theme-minimal
title: ğŸ‘¨ğŸ»â€ğŸ’»ğŸ’»ğŸ“„ğŸŒŸ
description: Hi, I'm Oliver. I am a DevOps Engineer who has been in the industry since January, 2022. I started my journey through a Civil Service apprenticeship in DevOps Engineering at DWP Newcastle.